Bears-R-Us/arkouda-contrib

CONTRIBUTING.md
README.md

This PR (closes #18):
`CONTRIBUTING.md` added with contribution details. `README.md` has been updated to link to `CONTRIBUTING.md`. 
This is just a basic start that will probably need to evolve as this repository evolves, but figured we should have a starting point.

Closes #18 Add `CONTRIBUTING.md`

---

ETL-CSV-to-HDF5/.gitignore
ETL-CSV-to-HDF5/client/README.md
ETL-CSV-to-HDF5/client/hdflow/__init__.py
ETL-CSV-to-HDF5/client/hdflow/converters.py
ETL-CSV-to-HDF5/client/hdflow/example_formats.py
ETL-CSV-to-HDF5/client/hdflow/scripts/csv2hdf
ETL-CSV-to-HDF5/client/setup.py

This is updated code compared to the existing hdflow in the main arkouda source. Putting it here for now, probably worth having a discussion on whether this should replace/merge into the main repo or if hdflow should be pulled out into contrib.

Adding updated hdflow source code

---

arkouda_BlockArrays2D/server/Arr2DMsg.chpl
arkouda_distance_wserver/server/distanceMsg.chpl
module_configuration.py

PR https://github.com/Bears-R-Us/arkouda/pull/1606 updates the modular build process to initialize modules on the command line and removes the need for `registerMe()`.
This PR updates the contrib repo to be compatible with those changes.

Update contrib repo modules and scripts with new modular build changes

---

arkouda_metrics_exporter/client/README.md
arkouda_metrics_exporter/client/arkouda_metrics_exporter/metrics.py
arkouda_metrics_exporter/client/setup.py
arkouda_metrics_exporter/pytest.ini
arkouda_metrics_exporter/test/metrics/base_test.py
arkouda_metrics_exporter/test/metrics/metrics_exporter_test.py

This PR corresponds to the arkouda_metrics_exporter project that enables the export of Arkouda metrics to Prometheus by way of a prometheus_client-based approach

44_arkouda_metrics_exporter

---

arkouda_integration/README.md
arkouda_integration/client/arkouda_integration/k8s.py
arkouda_integration/client/scripts/pods.py
arkouda_integration/client/setup.py
arkouda_integration/test/arkouda_integration_test.py

This PR contains the initial version of the arkouda_integration project that encapsulates create/read/delete logic required to integrate Arkouda instances with external systems with an initial focus upon Kubernetes.

add arkouda integration python library

---

arkouda_metrics_exporter/client/arkouda_metrics_exporter/metrics.py

This PR addresses #59 by updating arkouda_metrics_exporter/metrics.py per Arkouda msg format changes

updated arkouda client code per msg format changes #59

---

arkouda-docker/README.md
arkouda-docker/arkouda-full-stack
arkouda-docker/arkouda-smp-server
arkouda-docker/arkouda-udp-server
arkouda-docker/chapel-gasnet-udp
arkouda-docker/scripts/start-arkouda-locale.sh
arkouda-docker/scripts/start-arkouda-server.sh
arkouda-docker/scripts/start-smp-arkouda-full-stack-notebook.sh
arkouda-docker/scripts/start-smp-arkouda-full-stack.sh
arkouda-docker/scripts/start-smp-arkouda-server.sh

The arkouda-docker project provides Dockerfiles for a variety of Arkouda deployments along with corresponding scripts and README content

add arkouda-docker to arkouda contrib

---

aksparse/client/aksparse/backup/README.bak
aksparse/client/aksparse/backup/__init__.bak
aksparse/client/aksparse/backup/helpers.bak
aksparse/client/aksparse/backup/matrix.bak
aksparse/client/aksparse/matrix.py

This is a work-in-progress update to aksparse, however, the some basic classes and functions have been implemented in a manner matching scipy.

Updated aksparse, brought in line with scipy

---

arkouda-docker/README.md
arkouda-docker/chapel-gasnet-udp

Closes #71 
1. refactored arkouda-udp-server Dockerfile to decrease image size
2. updated README

arkouda-docker: refactor arkouda-udp-server and update README

---

arkouda-docker/README.md
arkouda-docker/arkouda-full-stack

Closes #76 
This PR does the following:
1. fixes arkouda-full-stack ENTRYPOINT (file naming issue)
2. upgrades README to latest arkouda version

76 update arkouda full stack dockerfile add to docs

---

arkouda_metrics_exporter/client/arkouda_metrics_exporter/metrics.py

Closes #80 
This PR enables pull of avg response time from Arkouda and enables scraping of avg response time logic from Prometheus

add avg response time support

---

arkouda_metrics_exporter/client/arkouda_metrics_exporter/metrics.py

Closes #82 
This PR adds logic to process, update, and provide Prometheus scrape targets for new Arkouda TOTAL_RESPONSE_TIME and TOTAL_MEMORY_USED metrics

added logic to process and update TOTAL_RESPONSE_TIME and TOTAL_MEMORY_USED

---

aksparse/client/setup.py
aksparse/pytest.ini

Made some minor adjustments to conform to the module install requirements.

Small changes to fit module requirements

---

aksparse/client/aksparse/__init__.py
aksparse/client/aksparse/sparse.py
aksparse/client/setup.py

Fixed a few misconfigurations is the arkouda-contrib module installation process, and made the process for enabling "Arkouda-function" SpGeMM uniform by cleaning up args for each required function.

Installation fixes + cleaned up Arkouda-SpGeMM functionality

---

arkouda_distance_wserver/server/DistanceCalcMsg.chpl

This PR (closes #97) updates arkouda_distance_wserver

Closes #97: Update arkouda_distance_wserver

---

arkouda-docker/README.md

Closes #114 
This PR updates the Docker images to Arkouda v2023.09.06

upgraded to v2023.09.06

---

arkouda_viz/client/arkouda_viz/viz.py

fixed a botched datashader import and removed leftover tabbing code

error cleanup

---

arkouda_cws_hashing/server/lshMinMax.chpl
arkouda_cws_hashing/server/lshMinMaxMsg.chpl

This PR (closes #130) updates the cws hashing code to compile with the latest version of arkouda and chpl

Closes #130: Update CWS Hashing

---

arkouda_viz/client/arkouda_viz/viz.py

x and y dropdown widgets added

---

arkouda-docker/README.md

updated README per user feedback

---

arkouda_workflows/README.md
arkouda_workflows/delete-arkouda-on-kubernetes-workflow-template.yaml
arkouda_workflows/delete-prometheus-arkouda-exporter-command.sh
arkouda_workflows/delete-prometheus-arkouda-exporter-workflow-template.yaml
arkouda_workflows/deploy-arkouda-on-kubernetes-command.sh
arkouda_workflows/deploy-arkouda-on-kubernetes-workflow-template.yaml
arkouda_workflows/deploy-prometheus-arkouda-exporter-command.sh
arkouda_workflows/deploy-prometheus-arkouda-exporter-workflow-template.yaml

Closes #152 
This PR delivers Prometheus discovery of prometheus-arkouda-exporter scrape targets via ServiceMonitors

add service monitor deployment for arkouda helm charts

---

arkouda-docker/README.md

Closes #159 - Upgrade arkouda-docker to v2024.03.18

---

arkouda-docker/README.md
arkouda_metrics_exporter/client/arkouda_metrics_exporter/metrics.py

enhance arkouda metrics exporter

---

arkouda-docker/README.md
arkouda-helm-charts/arkouda-udp-locale/Chart.yaml
arkouda-helm-charts/arkouda-udp-locale/README.md
arkouda-helm-charts/arkouda-udp-locale/templates/deployment.yaml
arkouda-helm-charts/arkouda-udp-locale/values.yaml
arkouda-helm-charts/arkouda-udp-server/Chart.yaml
arkouda-helm-charts/arkouda-udp-server/README.md
arkouda-helm-charts/arkouda-udp-server/templates/arkouda-server-launch-script-config-map.yaml
arkouda-helm-charts/arkouda-udp-server/templates/deployment.yaml
arkouda-helm-charts/arkouda-udp-server/templates/pod-binding.yaml
arkouda-helm-charts/arkouda-udp-server/templates/service-binding.yaml
arkouda-helm-charts/arkouda-udp-server/values.yaml
arkouda_integration/client/arkouda_integration/k8s.py
arkouda_integration/client/scripts/pods.py
arkouda_workflows/README.md
arkouda_workflows/arkouda-workflows-service-account.yaml
arkouda_workflows/deploy-arkouda-on-kubernetes-command.sh
arkouda_workflows/deploy-arkouda-on-kubernetes-workflow-template.yaml

This PR does the following:
1. Converts arkouda-helm-chart and arkouda_workflows to ServiceAccount/bearer token authentication
2. Refactors arkouda_integration k8s python client to use bearer token authentication

convert tls to service account

---

arkouda-docker/README.md
arkouda-docker/arkouda-udp-server
arkouda-helm-charts/arkouda-udp-locale/Chart.yaml
arkouda-helm-charts/arkouda-udp-locale/README.md
arkouda-helm-charts/arkouda-udp-locale/values.yaml
arkouda-helm-charts/arkouda-udp-server/Chart.yaml
arkouda-helm-charts/arkouda-udp-server/README.md
arkouda-helm-charts/arkouda-udp-server/values.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/Chart.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/values.yaml
arkouda_workflows/deploy-arkouda-on-kubernetes-workflow-template.yaml

cleanup arkouda workflows and arkouda helm charts

---

arkouda-docker/README.md
arkouda-docker/arkouda-integration
arkouda-helm-charts/arkouda-udp-locale/Chart.yaml
arkouda-helm-charts/arkouda-udp-locale/README.md
arkouda-helm-charts/arkouda-udp-locale/templates/arkouda-locale-launch-script-config-map.yaml
arkouda-helm-charts/arkouda-udp-locale/templates/deployment.yaml
arkouda-helm-charts/arkouda-udp-locale/values.yaml
arkouda-helm-charts/arkouda-udp-server/Chart.yaml
arkouda-helm-charts/arkouda-udp-server/README.md
arkouda-helm-charts/arkouda-udp-server/templates/arkouda-metrics-exporter-service.yaml
arkouda-helm-charts/arkouda-udp-server/templates/arkouda-server-launch-script-config-map.yaml
arkouda-helm-charts/arkouda-udp-server/templates/deployment.yaml
arkouda-helm-charts/arkouda-udp-server/templates/servicemonitor.yaml
arkouda-helm-charts/arkouda-udp-server/values.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/Chart.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/README.md
arkouda-helm-charts/prometheus-arkouda-exporter/templates/deployment.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/templates/servicemonitor.yaml
arkouda-helm-charts/prometheus-arkouda-exporter/values.yaml
arkouda_workflows/README.md
arkouda_workflows/delete-arkouda-on-kubernetes-cronworkflow.sh
arkouda_workflows/deploy-arkouda-on-kubernetes-command.sh
arkouda_workflows/deploy-arkouda-on-kubernetes-cronworkflow.sh
arkouda_workflows/deploy-arkouda-on-kubernetes-workflow-template.yaml

This PR encompasses the following:
1. Adds ServiceMonitor to prometheus-arkouda-exporter helm chart
2. Streamlines default values configuration in arkouda-helm-charts
3. Removes unneeded variables in arkouda-helm-charts
4. Updates arkouda-helm-charts and arkouda_workflows README files

170 update arkouda on kubernetes documentation
